# Generated by Django 3.2.6 on 2022-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=2, upload_to='images/users/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
