# Generated by Django 4.0 on 2022-01-10 13:07

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_news_category_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ ساخت'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ انتشار'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاريخ تغيير'),
        ),
    ]
