# Generated by Django 4.0 on 2022-01-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_news_created_alter_news_publish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comments',
        ),
    ]
